/**
 * Generates dist/sw.js after a build.
 *
 * Hand-rolled instead of workbox: the app is a fixed, small set of files, so the
 * whole service worker is a precache list plus a cache-first fetch handler. The
 * app must work with no signal, so EVERYTHING ships in the precache.
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = join(ROOT, "dist");

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(DIST)
  // _headers is a Cloudflare build directive, not a file the app ever fetches.
  .filter((f) => !f.endsWith("sw.js") && !f.endsWith("_headers"))
  .map((f) => "./" + relative(DIST, f).split("\\").join("/"))
  .sort();

// Version the cache by content, so a rebuild invalidates it and a rebuild that
// changes nothing does not.
const hash = createHash("sha1");
for (const f of files) hash.update(readFileSync(join(DIST, f.slice(2))));
const version = hash.digest("hex").slice(0, 12);

const bytes = files.reduce((n, f) => n + statSync(join(DIST, f.slice(2))).size, 0);

const sw = `// generated by scripts/make-sw.ts - do not edit
const CACHE = "valo-assistant-${version}";
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;

  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req)
        .then((res) => {
          // Cache anything new we fetched successfully, then serve it.
          if (res.ok && res.type === "basic") {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        // Offline and not cached: a navigation still gets the app shell.
        .catch(() => (req.mode === "navigate" ? caches.match("./index.html") : Response.error()));
    }),
  );
});
`;

writeFileSync(join(DIST, "sw.js"), sw);
console.log(`sw.js: ${files.length} files precached, ${(bytes / 1024 / 1024).toFixed(2)} MB, cache valo-assistant-${version}`);
